# nvfetcher.toml
[airflow-release]
src.github = "apache/airflow"
src.github_tag = "2.1.1"
fetch.github = "apache/airflow"

[airflow-latest]
src.git = "https://github.com/apache/airflow"
fetch.github = "apache/airflow"

# [airflow-source]
# src.github = "apache/airflow"
# fetch.url = "https://github.com/apache/airflow/releases/download/$ver/apache-airflow-$ver-source.tar.gz"
# src.prefix = "v"

[apache-airflow-providers-http]
src.pypi = "apache-airflow-providers-http"
fetch.pypi = "apache-airflow-providers-http"


[apache-airflow-providers-imap]
src.pypi = "apache-airflow-providers-imap"
fetch.pypi = "apache-airflow-providers-imap"

[apache-airflow-providers-sqlite]
src.pypi = "apache-airflow-providers-sqlite"
fetch.pypi = "apache-airflow-providers-sqlite"

[apache-airflow-providers-ftp]
src.pypi = "apache-airflow-providers-ftp"
fetch.pypi = "apache-airflow-providers-ftp"
